### ISSUE TITLE
[Introducing Language Integrated Queries] Issue while joining with a table

### ISSUE THREAD

**Issue by pcnfernando** [ballerina-platform/community#13]
**Description:**
The issue has been a index mismatch where I have considered an incorrect field for joining the table with data stream.

Please find the corrected demo content
[community-call 3.zip](https://github.com/ballerina-platform/community/files/7246316/community-call.3.zip)

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by samuelresowaski** [comment]
@pcnfernando Thank you for the files. I had to join your git repo. I cannot join slack channel. I am getting this error 
![image](https://user-images.githubusercontent.com/91563845/135144669-ea5244d9-5a2c-4a44-9ad3-1e2eee1551dc.png)

**Comment by pcnfernando** [comment]
Please check https://ballerina.io/community/slack/ and request for an invitation.

**Comment by samuelresowaski** [comment]
> @samuelresowaski Please check https://ballerina.io/community/slack/ and request for an invitation.

Thank you but that is the one giving me above error

**Comment by samuelresowaski** [comment]
> > @samuelresowaski Please check https://ballerina.io/community/slack/ and request for an invitation.
> 
> Thank you but that is the one giving me above error

Ok. I entered my email. How to request?

**Comment by pcnfernando** [comment]
@samuelresowaski  Are you already a team member? 
If not, you'll have to enter your email address https://ballerina.io/community/slack/#if-not-join-us and press enter to get an invitation.

**Comment by samuelresowaski** [comment]
> @samuelresowaski Are you already a team member? If not, you'll have to enter your email address https://ballerina.io/community/slack/#if-not-join-us and press enter to get an invitation.

ok. I didnt know I have to press enter. :) Thanks a lot!

**Comment by anupama-pathirage** [comment]
Closing as this  is done.
